import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import 'react-confirm-alert/src/react-confirm-alert.css'; // Import css
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@/styles/styles.css";
import AppHeader from "./components/app.header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SixDo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        {children}
        <footer className="bd-footer py-1 mt-1 bg-light align-items-md-center text-center">
          © 2024 SIXDO, by{" "}
          <a title="Solutions World" href="https://ssw.vn">
            ssw.vn
          </a>
        </footer>
      </body>
    </html>
  );
}
